"""
Django settings for meme_inator_back project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from core.secrets import read_secret
from dotenv import load_dotenv 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
# loads envionrment vars, parses key-val pairs, and injects them into os.environ
# will NOT override environ vars at system level. 
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'


ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.0.189').split(',')
# ALLOWED_HOSTS = [
#     'localhost',
#     '127.0.0.1',
#     '192.168.0.189',  # Far's Macbook computer's IP
#     # '192.168.0.*',     # Optional: allow all devices on your network
# ]


# Application definition

INSTALLED_APPS = [
    # Django applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django add-ons
    'ninja_extra',
    'ninja_jwt',
    'ninja_jwt.token_blacklist',
    
    # Meme-inator applications
    'apps.app_system',
    'apps.authentication',
    'apps.authorization',
    'apps.feeds',
    'apps.moderation_sys',
    'apps.posts',
    'apps.profiles',
    'apps.registration',
    'apps.users',
    'apps.commentsections',

    # Database related applications
    'django.contrib.postgres'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    
    # Default token lifetimes
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),  # Access token lifetime (e.g., 5 minutes) | 1 day for dev (ie 1440 minutes)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Refresh token lifetime (e.g., 1 day)

    # "Remember Me" token lifetimes
    'REMEMBER_ME_ACCESS_TOKEN_LIFETIME': timedelta(hours=1),     # 1 hour access
    'REMEMBER_ME_REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # 30 days refresh

    # TODO: Consider if refresh tokens should be rotated
    # Optional: allow refresh token rotation
    'ROTATE_REFRESH_TOKENS': False,

    # Optional: blacklist used refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,
}


# Add this when you have custom user. 
AUTH_USER_MODEL = 'users.UserModel'

ROOT_URLCONF = 'meme_inator_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meme_inator_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', 'meme_inator'),
        "USER": os.environ.get('DB_USER', 'far'),
        "PASSWORD": os.environ.get('DB_PASSWORD', ''),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CONFIG: Registration system
# Registration Application global variables
REGISTRATION_TOKEN_TTL_SECONDS = 60 * 15
DEREGISTRATION_CHALLENGE_TTL_SECONDS = 60 * 15
PASSWORD_RESET_CHALLANGE_TTL_SECONDS = 60 * 15
FRONTEND_URL = 'http://localhost:8000'
# buy domain from https://www.namecheap.com
# Use Mailtrap to test emails
# Email backend allows for email to print to terminal (simpliest way to dev)
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'accounts@meme-inator.com')

# CONFIG: Logging System
# Using Path (BASE_DIR) for cleaner path management
# LOG_BASE_DIR = BASE_DIR / 'logs'
# LOG_BASE_DIR.mkdir(parents=True, exist_ok=True)

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {asctime} {module}: {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.handlers.RotatingFileHandler',  # Changed this from FileHander
#             'filename': LOG_BASE_DIR / 'app_debug.log',
#             'maxBytes': 1024 * 1024 * 5,  # 5 MB limit per file
#             'backupCount': 5,              # Keep last 5 log files (approx 25MB total)
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'apps': {
#             'handlers': ['console'], # ['console', 'file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'django': {
#             'handlers': ['console'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#         # ADD THIS: This is the secret to seeing the 500 error stack trace
#         'django.request': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },

#         'ninja_jwt': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#         'django.contrib.auth': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }



# CONFIG: Initalize secrets
# ... Apple IAP Secrets
# APPLE_IAP_PRIVATE_KEY = read_secret(
#     os.environ["APPLE_IAP_PRIVATE_KEY_PATH"]
# )

# APPLE_IAP_ISSUER_ID = read_secret(
#     os.environ["APPLE_IAP_ISSUER_ID_PATH"]
# )

# APPLE_IAP_KEY_ID = read_secret(
#     os.environ["APPLE_IAP_KEY_ID_PATH"]
# )

# APPLE_IAP_BUNDLE_ID = read_secret(
#     os.environ["APPLE_IAP_BUNDLE_ID_PATH"]
# )
