from enum import Enum

class ProfileErrorCode(str, Enum):
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_CREATION_ERROR = "PROFILE_CREATION_ERROR"
    PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    DB_ERROR = "DB_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"