from enum import Enum


class WebhookEventType(str, Enum):
    CONTENT_ACCEPTED = "CONTENT_ACCEPTED"
    CONTENT_REJECTED = "CONTENT_REJECTED"
    CONTENT_FLAGGED = "CONTENT_FLAGGED"
    APPEAL_RESOLVED = "APPEAL_RESOLVED"
    PROVIDER_SWITCHED = "PROVIDER_SWITCHED"
    
class WebhookDeliveryStatus(str, Enum):
    PENDING = "PENDING"
    DELIVERED = "DELIVERED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"
    RETRYING = "RETRYING"