from enum import Enum

class FeedsErrorCode(str, Enum):
    DB_ERROR = "DB_ERROR"
    UNSUPPORTED_FEED_TYPE = "UNSUPPORTED_FEED_TYPE"
    INVALID_CURSOR = "INVALID_CURSOR"
    INVALID_DURATION_UNIT = "INVALID_DURATION_UNIT"
    INVALID_DURATION_WINDOW_SIZE = "INVALID_DURATION_WINDOW_SIZE"
    FEED_NOT_FOUND = "FEED_NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
